server:
  port: 8080
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://debug-registry:3306/activiti?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
