server:
   port: 8080
spring:
   freemarker:
      charset: UTF-8
      request-context-attribute: request
      settings:
         classic_compatible: true
         number_format: 0.##
      suffix: .ftl
      templateEncoding: UTF-8
      templateLoaderPath: classpath:/templates/
fastdfs:
   upload_location: E:\\develop\\upload\\
   priview_url: http://debug-registry:8888/