server:
   port: 8080
spring:
   type: com.alibaba.druid.pool.DruidDataSource
   datasource:
      url: jdbc:mysql://debug-registry:3306/ureport?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
   main:
      allow-bean-definition-overriding: true
logback:
   logPath: /ureport/log
   level: INFO