server:
  port: 8080
dubbo:
  scan:
    base-packages: com.xuzhihao.shop.dubbo.service # 开启包扫描
  protocols:
    dubbo:
      name: dubbo # 服务协议
      port: -1 # 服务端口
  registry:
    address: spring-cloud://debug-registry # 注册中心