server:
   port: 8080
dubbo:
   application:
      name: dubbo-provider
   registry:
      address: zookeeper://debug-registry:2181 #N/A
   scan:
      base-packages: ccom.xuzhihao.shop.dubbo.service